language: node_js
node_js:
  - '8'
install: 
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
cache: yarn
script:
  - yarn
  - yarn flow:remove
  - yarn test -- --runInBand --coverage